### ISSUE TITLE
Global reEntrancyMutex for all users.

### ISSUE THREAD

**Issue by kamal3951** [sigp/solidity-security-blog#19]
Hey,
In the Reentrancy Attack prevention contract, the `reEntrancyMutex` variable is global and the same for all users, if a user calls the `withdrawFunds()` when some other user has already called the function and the  `reEntrancyMutex` is set to `true` (the code is at line [23] suppose), the require condition for the new caller will not be met. Should not we have separate  `reEntrancyMutex` for different addresses? But then it will be of no use since we already have `lastWithdrawTime` variable. 
Thanks, please let me know if I should work on this issue.

**Comment by roirh** [comment]
Transactions in Ethereum are executed one by one, there is no multiprocessing.
Even in other blockchains that allow some degree of paralelism, if multiple transactions use a single contract, they are executed one by one.
So there is no problem at all in setting only one mutex variable.

**Comment by kamal3951** [comment]
Okay, thanks.
