### ISSUE TITLE
how about to get the pre_address of deploy a contract

### ISSUE THREAD

**Issue by zxhubo** [sigp/solidity-security-blog#3]
the method is determine future contract addresses  :
 // determine future addresses which can hide ether. 
    function futureAddresses(uint8 nonce) public view returns (address) {
        if(nonce == 0) {
            return address(keccak256(0xd6, 0x94, this, 0x80));
        }
        return address(keccak256(0xd6, 0x94, this, nonce));
    // need to implement rlp encoding properly for a full range of nonces
    }
now ,I don't know how to determine future addresses  is  return address(keccak256(0xd6, 0x94, this, 0x80)); and   return address(keccak256(0xd6, 0x94, this, nonce)); why use 0xd6 ,0x94,and when nonce is 0,use 0x80 . 
sorry ,my english is  poor， can you  understand and help me

**Comment by AgeManning** [comment]
It is because the parameters that are being hashed are RLP encoded. See this: https://github.com/ethereum/wiki/wiki/RLP for understanding RLP encoding. 
The empty string has 0x80 as you can see from the examples given in the link. 

Hope this helps :)

**Comment by zxhubo** [comment]
@AgeManning 
thank you very much for your help

**Comment by zxhubo** [comment]
0x94 is decimal 148,and 148 = 128+20.Because the  address is 20 bytes,so the length is 20.this i have know it,but 0xd6 is decimal 214,i can't  understand what's the meaning of 214. could you help me ,thanks.

**Comment by zxhubo** [comment]
@AgeManning

**Comment by AgeManning** [comment]
Notice the 4th point in the RLP encoding definition. "If the total payload is 0-55 bytes long.... a single bytes with value 0xc0 plus the length of the list..." 

0xc0 = 192 (in decimal). Thus, 0xd6 = 214, means the length of the total payload is 214-192 = 22. This indicates that 22 bytes are in the payload (1 byte length, 20 bytes address, 1 byte nonce). 

Hope this answers the question. :)
