### ISSUE TITLE
add some enumeration to the list

### ISSUE THREAD

**Issue by eMarchenko** [sigp/solidity-security-blog#5]
I'm working on [classification](https://github.com/smartdec/classification) of smart contract vulnerabilities. It would be so helpful if I could link to the items using some short tag like `SP-2`. Currently I have little choice other than use names of those items (like `Arithmetic Over/Under Flows`).

**Comment by AgeManning** [comment]
I've added numbers to each list item. I've added references, SP-1, SP-2 etc.. for each enumerated item. Let me know if this doesn't fit your needs.

**Comment by eMarchenko** [comment]
Well links have just stopped working.
Please check them (e.g. [SP-6](https://github.com/sigp/solidity-security-blog#SP-6)).

**Comment by AgeManning** [comment]
The html links are designed to work for the blog post (which has better formatting) not the github readme. 
See e.g [SP-6](https://blog.sigmaprime.io/solidity-security.html#SP-6)
